version: '3.8'
services:
  mongo:
    container_name: mongo
    image: mongo:4-focal
    volumes:
      - mongo-data:/data/db
    restart: always
    expose:
      - "27017"
  server:
    container_name: server
    image: server
    build: ./server
    ports:
      - 4000:4000
    links:
      - mongo
    depends_on:
      - mongo
    restart: always
    environment:
      MONGO_URL: mongo
  client:
    container_name: client
    image: client
    build: ./client
    ports:
      - 80:80
    links:
      - server
    depends_on:
      - server
    restart: always
    environment:
      API_URL: server
volumes:
  mongo-data: {}
